### PR TITLE
Rewrite car endpoint with xray and lodash

### PR DESCRIPTION
**Pull request by benediktvaldez**
For v2

ps: probably deserves a version bump :)

### CODE REVIEW

**Comment by koddsson** [comment]
Is this supposed to go into master?

**Comment by MiniGod** [comment]
`master` of apis does not use this package, so `car` is not really in use anywhere yet.

**Comment by benediktvaldez** [comment]
@MiniGod I already made a pull request for apis/v2 to include this

https://github.com/kristjanmik/apis/pull/194

**Comment by MiniGod** [comment]
@benediktvaldez: I was replying to @koddsson :)

**Pull request merged**
